return {
--     {
--         "mfussenegger/nvim-dap",
--         dependencies = {
--             -- UI del depurador
--             {
--                 "rcarriga/nvim-dap-ui",
--                 dependencies = {
--                     "nvim-neotest/nvim-nio", -- ⬅️ esta es la dependencia obligatoria nueva
--                 },
--             },
--             "williamboman/mason.nvim",
--             "jay-babu/mason-nvim-dap.nvim",
--         },
--         event = "VeryLazy",
--         config = function()
--             local dap = require("dap")
--             local dapui = require("dapui")
--
--             dapui.setup()
--
--             dap.listeners.after.event_initialized["dapui_config"] = function()
--                 dapui.open()
--             end
--             dap.listeners.before.event_terminated["dapui_config"] = function()
--                 dapui.close()
--             end
--             dap.listeners.before.event_exited["dapui_config"] = function()
--                 dapui.close()
--             end
--
--             -- Keymaps
--             vim.keymap.set("n", "<F5>", dap.continue)
--             vim.keymap.set("n", "<F10>", dap.step_over)
--             vim.keymap.set("n", "<F11>", dap.step_into)
--             vim.keymap.set("n", "<F12>", dap.step_out)
--             vim.keymap.set("n", "<F9>", dap.toggle_breakpoint)
--             vim.keymap.set("n", "<Leader>B", function()
--                 dap.set_breakpoint(vim.fn.input("Condición: "))
--             end)
--
--             -- Configuración para Node.js / NestJS
--             dap.adapters.node2 = {
--                 type = "executable",
--                 command = "node",
--                 args = {
--                     vim.fn.stdpath("data") .. "/mason/packages/node-debug2-adapter/out/src/nodeDebug.js",
--                 },
--             }
--
--             dap.configurations.typescript = {
--                 {
--                     name = "NestJS attach (debug)",
--                     type = "node2",
--                     request = "attach",
--                     port = 9229,
--                     restart = true,
--                     protocol = "inspector",
--                     sourceMaps = true,
--                     outFiles = { "${workspaceFolder}/dist/**/*.js" },
--                 },
--                 {
--                     name = "NestJS launch main.ts",
--                     type = "node2",
--                     request = "launch",
--                     program = "${workspaceFolder}/src/main.ts",
--                     runtimeArgs = { "--nolazy", "-r", "ts-node/register" },
--                     cwd = "${workspaceFolder}",
--                     protocol = "inspector",
--                     outFiles = { "${workspaceFolder}/dist/**/*.js" },
--                     sourceMaps = true,
--                     skipFiles = { "<node_internals>/**", "node_modules/**" },
--                 },
--             }
--         end,
--     },
--
--     {
--         "jay-babu/mason-nvim-dap.nvim",
--         opts = {
--             ensure_installed = { "python", "node2" }, -- instala los adaptadores automáticamente
--             automatic_installation = true,
--         },
--     },
}
